import { GalleryImage, Project, BlogPost } from './types';

export const IMAGES: GalleryImage[] = [
  {
    id: '1',
    url: '/36JPGSUbumuntu.jpeg',
    title: 'Ubumuntu Performance I',
    category: 'event',
    width: 2070,
    height: 1380,
  },
  {
    id: '2',
    url: '/100JPGSUbumuntu.jpeg',
    title: 'Ubumuntu Performance II',
    category: 'event',
    width: 2070,
    height: 1380,
  },
  {
    id: '3',
    url: '/116JPGSUbumuntu.jpeg',
    title: 'Ubumuntu Performance III',
    category: 'event',
    width: 2070,
    height: 1380,
  },
  {
    id: '4',
    url: '/119JPGSUbumuntu.jpeg',
    title: 'Ubumuntu Festival Culture',
    category: 'event',
    width: 2070,
    height: 1380,
  },
  {
    id: '5',
    url: '/121JPGSUbumuntu.jpeg',
    title: 'Ubumuntu Stage Moments',
    category: 'event',
    width: 2070,
    height: 1380,
  },
  {
    id: '6',
    url: '/134JPGSUbumuntu.jpeg',
    title: 'Ubumuntu Artistry',
    category: 'event',
    width: 2070,
    height: 1380,
  },
  {
    id: '7',
    url: '/136JPGSUbumuntu.jpeg',
    title: 'Ubumuntu Grand Finale',
    category: 'event',
    width: 2070,
    height: 1380,
  },
  {
    id: '8',
    url: '/43JPGSUbumuntu.jpeg',
    title: 'Ubumuntu Expression',
    category: 'event',
    width: 2070,
    height: 1380,
  },
  {
    id: '9',
    url: '/61JPGSUbumuntu.jpeg',
    title: 'Ubumuntu Behind Scenes',
    category: 'event',
    width: 2070,
    height: 1380,
  },
  {
    id: '10',
    url: '/gaby.jpeg',
    title: 'Portrait Study',
    category: 'portrait',
    width: 1200,
    height: 1200,
  },
  {
    id: '11',
    url: '/b1.jpeg',
    title: 'Urban Focus',
    category: 'street',
    width: 1965,
    height: 1310,
  },
  {
    id: '12',
    url: '/b2.jpeg',
    title: 'Soulful Lighting',
    category: 'portrait',
    width: 1976,
    height: 1317,
  },
  {
    id: '13',
    url: '/fll.jpeg',
    title: 'FLL Robotics Competition',
    category: 'event',
    width: 1200,
    height: 1200,
  },
  {
    id: '14',
    url: '/Finals_20.JPG',
    title: 'Kigali Breaking Festival Finals I',
    category: 'event',
    width: 2000,
    height: 1333,
  },
  {
    id: '15',
    url: '/Finals_33.JPG',
    title: 'Kigali Breaking Festival Finals II',
    category: 'event',
    width: 2000,
    height: 1333,
  },
  {
    id: '16',
    url: '/Finals_34.JPG',
    title: 'Kigali Breaking Festival Finals III',
    category: 'event',
    width: 2000,
    height: 1333,
  },
  {
    id: '17',
    url: '/Finals_50.JPG',
    title: 'Kigali Breaking Festival Finals IV',
    category: 'event',
    width: 2000,
    height: 1333,
  },
  {
    id: '18',
    url: '/KBF-Preselections_32.JPG',
    title: 'Kigali Breaking Festival Preselections I',
    category: 'event',
    width: 2000,
    height: 1333,
  },
  {
    id: '19',
    url: '/KBF-Preselections_72.JPG',
    title: 'Kigali Breaking Festival Preselections II',
    category: 'event',
    width: 2000,
    height: 1333,
  },
  {
    id: '20',
    url: '/institutFrancais_30.JPG',
    title: 'Institut Français Showcase I',
    category: 'event',
    width: 2000,
    height: 1333,
  },
  {
    id: '21',
    url: '/institutFrancais_45.JPG',
    title: 'Institut Français Showcase II',
    category: 'event',
    width: 2000,
    height: 1333,
  },
  {
    id: '22',
    url: '/institutFrancais_49.JPG',
    title: 'Institut Français Showcase III',
    category: 'event',
    width: 2000,
    height: 1333,
  },
  {
    id: '23',
    url: '/institutFrancais_7.JPG',
    title: 'Institut Français Showcase IV',
    category: 'event',
    width: 2000,
    height: 1333,
  },
  {
    id: '24',
    url: '/institutFrancais_77.JPG',
    title: 'Institut Français Showcase V',
    category: 'event',
    width: 2000,
    height: 1333,
  }
];

export const PROJECTS: Project[] = [
  {
    id: 'p1',
    title: 'Kigali Breaking Festival',
    category: 'Event',
    coverUrl: '/KBF-Preselections_72.JPG',
    description: 'A festival-focused documentation capturing the energy, movement, and emotion of Kigali Breaking Festival across its most memorable moments.',
    images: IMAGES.filter(i => i.url.toLowerCase().includes('kbf') || i.url.toLowerCase().includes('finals') || i.url.toLowerCase().includes('institutfrancais')),
    additionalLinks: [
      { label: 'Finals', url: 'https://shusho67.pixieset.com/kbffinals1/' },
      { label: 'Preselections', url: 'https://shusho67.pixieset.com/kbfpreselections1/' },
      { label: 'Institut Français', url: 'https://shusho67.pixieset.com/institutfrancais1/' },
      { label: 'Workshop', url: 'https://shusho67.pixieset.com/kbfworkshop/' },
    ],
  },
  {
    id: 'p2',
    title: 'FLL Robotics Competition',
    category: 'Event',
    coverUrl: '/fll.jpeg',
    description: 'A portrait-focused series that highlights poise, character, and visual storytelling through careful composition.',
    images: IMAGES.filter(i => i.url.toLowerCase().includes('gaby') || i.url.toLowerCase().includes('fll')),
  },
  {
    id: 'p3',
    title: 'Kwibuka 32',
    category: 'Commemoration',
    coverUrl: '/119JPGSUbumuntu.jpeg',
    description: 'Documenting reflective public moments with a focus on atmosphere, crowd presence, and human connection.',
    images: IMAGES.filter(i => ['4', '5', '6'].includes(i.id)),
  },
  {
    id: 'p4',
    title: 'Ubumuntu Art Festival',
    category: 'Event',
    coverUrl: '/36JPGSUbumuntu.jpeg',
    description: 'A visual documentation of the Ubumuntu Arts Festival, exploring humanity through performance and dance.',
    images: IMAGES.filter(i => i.url.toLowerCase().includes('ubumuntu')),
  },
  {
    id: 'p5',
    title: 'Urban Perspectives',
    category: 'Street',
    coverUrl: '/b1.jpeg',
    description: 'Exploring the vibrant streets of Kigali, capturing the raw energy and daily rhythms of city life.',
    images: IMAGES.filter(i => i.category === 'street'),
  }
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'b1',
    title: 'Urban Rhythms: Kigali Streets',
    excerpt: 'Exploring the silent stories and vibrant energy hidden within the everyday bustle of the city.',
    content: 'The street is a living, breathing organism, constantly evolving and shifting. Capturing its essence requires patience and a keen eye for the moments that usually go unnoticed...',
    date: 'May 1, 2026',
    imageUrl: '/116JPGSUbumuntu.jpeg',
    category: 'Street',
  },
  {
    id: 'b2',
    title: 'The Soul of the Portrait',
    excerpt: 'How golden hour lighting can transform a simple portrait into a deep study of character.',
    content: 'Portraiture is more than just capturing a face; it is about capturing a soul. By leveraging the soft, warm light of the late afternoon, we can bring out textures and emotions...',
    date: 'April 20, 2026',
    imageUrl: '/b2.jpeg',
    category: 'Portrait',
  },
];
