import { GalleryImage, Project, BlogPost } from './types';

export const IMAGES: GalleryImage[] = [
  {
    id: '1',
    url: '/36JPGSUbumuntu.jpg',
    title: 'Ubumuntu Performance I',
    category: 'event',
    width: 2070,
    height: 1380,
  },
  {
    id: '2',
    url: '/100JPGSUbumuntu.jpg',
    title: 'Ubumuntu Performance II',
    category: 'event',
    width: 2070,
    height: 1380,
  },
  {
    id: '3',
    url: '/116JPGSUbumuntu.jpg',
    title: 'Ubumuntu Performance III',
    category: 'event',
    width: 2070,
    height: 1380,
  },
  {
    id: '4',
    url: '/119JPGSUbumuntu.jpg',
    title: 'Ubumuntu Festival Culture',
    category: 'event',
    width: 2070,
    height: 1380,
  },
  {
    id: '5',
    url: '/121JPGSUbumuntu.jpg',
    title: 'Ubumuntu Stage Moments',
    category: 'event',
    width: 2070,
    height: 1380,
  },
  {
    id: '6',
    url: '/134JPGSUbumuntu.jpg',
    title: 'Ubumuntu Artistry',
    category: 'event',
    width: 2070,
    height: 1380,
  },
  {
    id: '7',
    url: '/136JPGSUbumuntu.jpg',
    title: 'Ubumuntu Grand Finale',
    category: 'event',
    width: 2070,
    height: 1380,
  },
  {
    id: '8',
    url: '/43JPGSUbumuntu.jpg',
    title: 'Ubumuntu Expression',
    category: 'event',
    width: 2070,
    height: 1380,
  },
  {
    id: '9',
    url: '/52JPGSUbumuntu.jpg',
    title: 'Ubumuntu Behind Scenes',
    category: 'event',
    width: 2070,
    height: 1380,
  },
  {
    id: '10',
    url: '/Intare1.jpg',
    title: 'Robotics Competition at Intare',
    category: 'event',
    width: 1974,
    height: 1316,
  },
  {
    id: '11',
    url: '/Kwib.314.JPG',
    title: 'Kwibuka Remembrance',
    category: 'event',
    width: 2070,
    height: 1380,
  },
  {
    id: '12',
    url: '/IMG_0443.jpg',
    title: 'Kigali Street Life I',
    category: 'street',
    width: 2070,
    height: 1380,
  },
  {
    id: '13',
    url: '/IMG_0448.jpg',
    title: 'Kigali Street Life II',
    category: 'street',
    width: 2070,
    height: 1380,
  },
  {
    id: '14',
    url: '/IMG_6339.jpg',
    title: 'Breaking Festival Energy',
    category: 'event',
    width: 2070,
    height: 1380,
  },
  {
    id: '15',
    url: '/IMG_6521.jpg',
    title: 'Urban Geometry',
    category: 'street',
    width: 2070,
    height: 1380,
  },
  {
    id: '16',
    url: '/IMG_6851.jpg',
    title: 'Daily City Hustle',
    category: 'street',
    width: 2070,
    height: 1380,
  },
  {
    id: '17',
    url: '/IMG_7422.jpg',
    title: 'Sunset Silhouettes',
    category: 'landscape',
    width: 2070,
    height: 1380,
  },
  {
    id: '18',
    url: '/_MG_2291.JPG',
    title: 'Classic Portrait Studio',
    category: 'portrait',
    width: 2070,
    height: 1380,
  },
  {
    id: '19',
    url: '/SnapInsta.to_542886789_18179496775341756_5790892256897626045_n.jpg',
    title: 'Modern Portrait Style',
    category: 'portrait',
    width: 1080,
    height: 1350,
  },
  {
    id: '20',
    url: '/s1_14.jpg',
    title: 'Natural Perspective',
    category: 'landscape',
    width: 2070,
    height: 1380,
  },
  {
    id: '21',
    url: '/b1.jpg',
    title: 'Urban Focus',
    category: 'street',
    width: 1965,
    height: 1310,
  },
  {
    id: '22',
    url: '/b2.jpg',
    title: 'Soulful Lighting',
    category: 'portrait',
    width: 1976,
    height: 1317,
  }
];

export const PROJECTS: Project[] = [
  {
    id: 'p1',
    title: 'FLL Robotics Competition',
    category: 'Event',
    coverUrl: '/Intare1.jpg',
    description: 'FLL competition in Intare Conference arena, showcasing the innovative spirit of young minds in robotics.',
    images: IMAGES.filter(i => i.url.toLowerCase().includes('intare')),
  },
  {
    id: 'p2',
    title: 'Kwibuka 32',
    category: 'Commemoration',
    coverUrl: '/Kwib.314.JPG',
    description: 'Honoring the memory and resilience through solemn photography during the commemoration period.',
    images: IMAGES.filter(i => i.url.toLowerCase().includes('kwib')),
  },
  {
    id: 'p3',
    title: 'Ubumuntu Art Festival',
    category: 'Event',
    coverUrl: '/36JPGSUbumuntu.jpg',
    description: 'A visual documentation of the Ubumuntu Arts Festival, exploring humanity through performance and dance.',
    images: IMAGES.filter(i => i.url.toLowerCase().includes('ubumuntu')),
  },
  {
    id: 'p4',
    title: 'Urban Perspectives',
    category: 'Street',
    coverUrl: '/IMG_6851.jpg',
    description: 'Exploring the vibrant streets of Kigali, capturing the raw energy and daily rhythms of city life.',
    images: IMAGES.filter(i => i.category === 'street'),
  }
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'b1',
    title: 'Urban Rhythms: Kigali Streets',
    excerpt: 'Exploring the silent stories and vibrant energy hidden within the everyday bustle of the city.',
    content: 'The street is a living, breathing organism, constantly evolving and shifting. Capturing its essence requires patience and a keen eye for the moments that usually go unnoticed...',
    date: 'May 1, 2026',
    imageUrl: '/116JPGSUbumuntu.jpg',
    category: 'Street',
  },
  {
    id: 'b2',
    title: 'The Soul of the Portrait',
    excerpt: 'How golden hour lighting can transform a simple portrait into a deep study of character.',
    content: 'Portraiture is more than just capturing a face; it is about capturing a soul. By leveraging the soft, warm light of the late afternoon, we can bring out textures and emotions...',
    date: 'April 20, 2026',
    imageUrl: '/IMG_7422.jpg',
    category: 'Portrait',
  },
];
